In [ ]:
#importing
import numpy as np

ARRAYS

In [ ]:
#creating 1D array
A=np.array([1,2,3,4,5])
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
#creating 2D array
B=np.array([[2,3,4],[5,6,7]])
print(B)

[[2 3 4]
 [5 6 7]]


In [ ]:
#creating a 3D array-rows,columns,groups
C=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(C)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#checking dimensions
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


In [ ]:
#ones
D=np.ones((2,3,3))
print(D)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#ones
E=np.ones((3,2)) #rows,columns,2D
print(E)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Zeros
F=np.zeros((3,2)) #2D
print(F)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
J=np.eye(4)
print(J)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
J=np.eye(4,3)
print(J)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
#arange
H=np.arange(3,31,3) #start,stop,step
print(H)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
G=np.arange(5,1001,5) #range of 5 multiples upto 1000
print(G)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [ ]:
#arange
H=np.arange(3,31,3).reshape(5,2)
print(H)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
V=np.linspace(12,24,10)
print(V)

[12.         13.33333333 14.66666667 16.         17.33333333 18.66666667
 20.         21.33333333 22.66666667 24.        ]


In [ ]:
W=np.linspace(1,2,6)
print(W)

[1.  1.2 1.4 1.6 1.8 2. ]


In [ ]:
W=np.linspace(1,2,4)
print(W)

[1.         1.33333333 1.66666667 2.        ]


In [ ]:
L=np.arange(1,7).reshape(2,3)
print(L)
R=np.arange(9,15).reshape(2,3)
print(R)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [ ]:
print(L+R)

[[10 12 14]
 [16 18 20]]


In [ ]:
G=np.sum((L,R))
print(G)

90


In [ ]:
G=np.sum((L,R),axis=0) #axis=0-columns,axis=1-rows,axis=2-groups
print(G)

[[10 12 14]
 [16 18 20]]


In [ ]:
G=np.sum((L,R),axis=1)
print(G)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=0))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=1))

[[4. 4.]
 [4. 4.]]


In [ ]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A*B)

[[2 0]
 [0 4]]


In [ ]:
print(A@B)

[[5 4]
 [3 4]]


In [ ]:
#b=np.array[25,289,361,81],find square roots and iterate through result values output:5 square is 25
b=np.array([25,289,361,81])
for i in b:
  print(np.sqrt(i),"square is",i)


5.0 square is 25
17.0 square is 289
19.0 square is 361
9.0 square is 81


In [ ]:
#array joins
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
print(a)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(b)
print(np.vstack((a,b))) #columns
print("\n")
print(np.hstack((a,b))) #rows

[[34 35 36]
 [37 38 39]]
[[4 5 6]
 [7 8 9]]
[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("output of dstack")
print(np.dstack(a))
#number of rows becomes number of groups
#colums becomes rows
#group becomes columns

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
output of dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
