In [ ]:
import numpy as np
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY

In [ ]:
A=np.random.rand(1)
print(A)

[0.00777167]


In [ ]:
A=np.random.rand(8,4) #rand->range is between 0 and 1
print(A)

[[0.35208612 0.69614847 0.9318546  0.99515729]
 [0.10632025 0.56098254 0.22869707 0.09081847]
 [0.03660847 0.14920508 0.86055775 0.50949763]
 [0.36834902 0.62752128 0.72599122 0.94451664]
 [0.68100767 0.12047075 0.45364201 0.79857384]
 [0.01256332 0.51994167 0.63913341 0.02055185]
 [0.26026288 0.44646042 0.48406288 0.35483949]
 [0.43617306 0.31202285 0.23839725 0.65423839]]


In [ ]:
A=10*np.random.rand(8,4)
print(A)

[[6.50182128 9.38981384 5.95932848 0.44327031]
 [5.81899241 1.64916831 6.67126309 1.0729848 ]
 [0.49574685 8.45974767 0.16888297 2.85829145]
 [5.98471116 6.7223841  2.87701833 6.47740956]
 [9.07535411 5.50039064 9.38304664 7.99664031]
 [1.05623039 7.49401692 9.16810254 1.2725668 ]
 [1.26254613 0.81298037 8.4304281  5.91284633]
 [9.78042782 6.27681645 7.69855508 6.84032999]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))
print(A)

[[2. 2. 7. 4.]
 [2. 1. 9. 3.]
 [0. 2. 6. 9.]
 [9. 8. 8. 0.]
 [9. 9. 3. 2.]
 [8. 0. 5. 7.]
 [7. 8. 6. 5.]
 [8. 6. 2. 1.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(A,4)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

:::::np.vsplit(A,4 #the spliting number should divide no.of rows.(8/4))

In [ ]:
np.vsplit(A,3)

ValueError: array split does not result in an equal division

In [ ]:
np.vsplit(A,(3,5)) #split it after 3rd row and 5th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
B=np.arange(1,33).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(B,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

Trigonometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
B=np.rad2deg(A)
print(B) #convert radians to degree

[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(B) #convert degree to radians

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1)

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

Statistics

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st) # std=sum of difference between observations/no.of observations

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
#inverse of matrix
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.arange(1,25).reshape(6,4)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(C))

23


In [ ]:
C=np.floor(10*np.random.rand(24)).reshape(6,4)
print(C)

[[0. 5. 2. 8.]
 [3. 4. 5. 9.]
 [9. 7. 6. 1.]
 [6. 0. 9. 2.]
 [7. 5. 4. 1.]
 [7. 8. 4. 9.]]


In [ ]:
C=10*np.random.rand(24).reshape(6,4)
print(C)

[[7.22623122 7.50182059 4.44914884 7.56952983]
 [0.82030736 8.25821264 7.67160853 1.55299334]
 [1.03847947 6.32690482 1.07567409 3.18030456]
 [4.27993202 6.85219537 1.96121837 5.79752947]
 [5.51536554 9.81234245 9.23142056 9.78580278]
 [3.08879664 4.154119   2.04746592 7.78669196]]


In [ ]:
print(np.argmax(C))

17


In [ ]:
print(np.argmax(C,axis=0))

[0 4 4 4]


In [ ]:
print(np.argmax(C,axis=1))

[3 1 1 1 1 3]


In [ ]:
print(np.argmin(C))

4


In [ ]:
print(np.argmin(C,axis=1))

[2 0 0 2 0 2]


In [ ]:
print(np.argmin(C,axis=0))

[1 5 2 1]


searching

In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))  #where condition is nothing but if.

(array([0, 1, 4]),)


In [ ]:
print(np.where(a%2!=0)) #printing odd numbers

(array([2, 3, 5]),)


In [ ]:
B=np.array([24,16,7,17,54,60])
print(np.where(B%6==0))

(array([0, 4, 5]),)


In [ ]:
#used only for already sorted list
a=np.array([1,2,4,6,8,9])
x=np.searchsorted(a,6)
print(x)

3


In [ ]:
#sorting array
import numpy as np
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))
#2nd example
arr=np.array(['TRUE','FALSE','TRUE'])
print(np.sort(arr))

['apple' 'banana' 'cherry']
['FALSE' 'TRUE' 'TRUE']


In [ ]:
#2D sort->sorting happens with in the row
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#filter
arr=np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)
arr[filt]

(array([0, 2, 3, 5]),)


array([40, 50, 44, 78])

In [ ]:
#iterating through two arrays
names=(['priya','samhitha','rishika','kriti'])
initials=(['s','R','Y','D'])
for i,j in zip(initials,names):  #do using list
   print(i,".",j)

s . priya
R . samhitha
Y . rishika
D . kriti


In [ ]:
# Multiplication of two  arrays
a1=np.array([10,20,30,40,50,60])
a2=np.array([11,21,31,41,51,61])
n=np.multiply(a1,a2)
print(n)


[ 110  420  930 1640 2550 3660]


In [ ]:
#division operation between two arrays
a1=np.array([31,32,33,34,35,36])
a2=np.array([11,12,13,14,15,16])
n=np.divide(a1,a2)
print(n)

[2.81818182 2.66666667 2.53846154 2.42857143 2.33333333 2.25      ]


In [ ]:
#modulo operation between two arrays
a1=np.array([1,2,3,4,5,6])
a2=np.array([11,12,13,14,15,16])
n=np.mod(a1,a2)
print(n)

[1 2 3 4 5 6]


In [ ]:
#modulodivision between two arrays
a1=np.array([31,32,33,34,35,36])
a2=np.array([11,12,13,14,15,16])
n=np.divmod(a1,a2)
print(n)

(array([2, 2, 2, 2, 2, 2]), array([9, 8, 7, 6, 5, 4]))


In [ ]:
#logarithms
a1=1.2
print(np.log(a1))  #natural log e

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a)) #log base 2

0.2630344058337938


In [ ]:
a=1.2
print(np.log10(a))  #lof base 10

0.07918124604762482


In [ ]:
a=np.array([1,1.2,3,4])
print(np.log(a))

[0.         0.18232156 1.09861229 1.38629436]


In [ ]:
#cummulative product
a=np.array([1,2,3,4,5])
x=np.cumprod(a)
print(x)

[  1   2   6  24 120]


In [ ]:
#cummulative sum
a=np.array([1,2,3,4,5])
x=np.cumsum(a)
print(x)

[ 1  3  6 10 15]


In [ ]:
#differnce
a=np.array([12,3,6,5])
x=np.diff(a)
print(x)

[-9  3 -1]


In [ ]:
#LCM
n1=25
n2=35
x=np.lcm(n1,n2)
print(x)

175


In [ ]:
#HCF
n1=25
n2=35
x=np.gcd(n1,n2)
print(x)

5


In [ ]:
a=np.array([12,15,60])
gc=np.gcd(a) #takes multiple inputs gives single output
print(gc)

TypeError: gcd() takes from 2 to 3 positional arguments but 1 were given

In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a) #takes multiple inputs gives single output
print(gc)

3


In [ ]:
a=np.array([12,15,60])
gc=np.lcm.reduce(a) #takes multiple inputs gives single output
print(gc)

60
